### ISSUE TITLE
Service won't start when seriesMap uses umlauts

### ISSUE THREAD

**Issue by Christoph21x** [ChrisRichner/ARGUS-TV-GuideEnhancer#10]
Dear Chris, dear All

Using seriesMapping I found a minor issue (but may be tricky to find it):
If you use a seriesMap with an umlaut, it:
- won't process it and launch an error (let's say: kind of "correct", but not "good")
- if you end the service or restart it, the service won't start and launches an error message "access denied"

I think I tried it with that one:
    - seriesMap schedulesDirectName="regex=Der Trödeltrupp*" tvdbComName="" ignore="true"

What I didn't try, was, how it would behave in a NON-regex expression like
    - seriesMap schedulesDirectName="Der Trödeltrupp" tvdbComName="" ignore="true"

Greetz - Chris

**Comment by Malyngo** [comment]
Can you check if the config file is saved as UTF-8? If I am not mistaken, this should not really be a problem to have umlauts in a regex.

**Comment by Christoph21x** [comment]
Correct: format is ANSI.
Re-Checked it with the following results:
1. ANSI: umlaut in a seriesMap leads to the above described error
2. UTF-8: error doesn't occur. Not yet checked, if the expressions really works. Currently I have only "ignore entries" with umlauts. I'll search for a fitting entry (series) and will launch test schedule after adding the mapping.

I'll be back with information.
In the meantime - how could we avoid this?

Greetz & (again) thanks, Malyngo - Chris

**Comment by Christoph21x** [comment]
Ok, managed to use it with a trick:
- had to find a series with an umlaut which is not "as is" in TheTVDB.
- which has either an episode name or s/e numbering
- Workaround: took one with an umlaut
- mapped it to another series by id 
to check if the map really works (and that it's not a "hit by default")

With UTF-8:
(seriesMap schedulesDirectName="regex=Köln 5.*" tvdbComName="id=254785")
This maps "Köln 50667" to Lindenstrasse :D (needed a series with at least 540 entries in TheTVDB)

Result: it works without any issue - all entries of Köln 50667 are mapped to the (absolute numbered) Lindenstrasse equivalents.

So: this is really just a file encoding issue.

Greetz - Chris
