### ISSUE TITLE
Can this be used in combination with WG+?

### ISSUE THREAD

**Issue by piejanssens** [ChrisRichner/ARGUS-TV-GuideEnhancer#12]
Any known issues when using this with WebGrab+?

**Comment by Christoph21x** [comment]
Nope, works like a charm. Depending on the site, from which WG++ grabs, you have to adjust the seeking sequence, of course.

GReetz - Chris

**Comment by piejanssens** [comment]
I see that the author of WG+ just released some plugin to support thetvdb.com, but this seems more advanced, so I'm going to try this out. Thanks a lot.
