### ISSUE TITLE
Proposal: common Mapping Repository (Github file)

### ISSUE THREAD

**Issue by Christoph21x** [ChrisRichner/ARGUS-TV-GuideEnhancer#14]
Importance: very low

Dear All

When browsing through EPG, every now and then I find new series to map.
What if we would create within the Github Repo a sub-directory (and maybe include the file also in the installer) that collects an xml file as a copy & paste-template for "seriesMapping"?

We could easily collect our findings.
I would cluster it in at least two sections:
- mappings
- ignores
which collect recommendations &/ series mappings to (probably) distinct IDs.

What u think? Chris would have just to add a file, to which we can commit, in the installer and drop a default note / referrer within the config file on top of the mapping section.
Everything els could be contributed by us through pull requests.

Greetz - Chris

**Comment by ChrisRichner** [comment]
Sound's great! I'll make this happen asap.

Keep the suggestions coming! ;)

Greetz
Chris

**Comment by ChrisRichner** [comment]
I've added the copy & paste-template file under \Setup\seriesmapping.xml.

In case that the structure is not the purposed one don't hesitate to change everything as needed. I assume that you can change the file directly as a contributor, no need to fork & pull request.

**Comment by Christoph21x** [comment]
Hi All
I re-worked the structure & working method and expanded the given start in order to have a combined template with embedded information.
Now:
1. I ask for your opinion
2. Chris, what is the difference (and which is the preferred method / perform faster / is more fundamental) of ignoring entries:
- within section (seriesMapping) like
	(!-- Castle --)
	(seriesMap schedulesDirectName="Castle" tvdbComName="" ignore="true"/)
- or within section (ignores) section like
	(!-- Castle --)
	(seriesMap schedulesDirectName="Castle" tvdbComName="id=83462"/)

Greetz & thanks to Chris - Chris

**Comment by ChrisRichner** [comment]
FYI: I've updated the readme.md in the develop branch. I've mentioned the seriesMapping.xml inside the mapping & FAQ section.

Suggestions & Feedback welcome!

**Comment by Christoph21x** [comment]
Thanks a lot, Chris!
Maybe you'd like to drop a message in the Argus-TV forum's thread? They also might drop suggestions in there - and we would add them...
Committing (do NOT confuse with vomit :) ) is working now...

I'll close this issue for now... Huge thanks for all of your work, Chris - Chris :)
