### ISSUE TITLE
Error causes Guide Enricher to stop

### ISSUE THREAD

**Issue by aswede** [ChrisRichner/ARGUS-TV-GuideEnhancer#16]
I am using Guide Enricher (2.3.0.42695) with Argus 2.3RC. I am not sure if there is a pattern to this, but usually after running Argus / GuideEnricher for 6-8 weeks I start having issues, beginning with Argus crashing. After rebooting Argus works fine, but GuideEnricher is not. In the log I will typically see something like what you can see from below - it seems GE is not able to match a show, using all different methods, and then it crashes.

If I disable the show just before the error, in Argus, and restart GuideEnricher the error re-occurs after not being able to match a different show.

Could you give some ideas what I should be looking for that may cause this error?

Thanks,

Anders

2015-03-09 06:45:17 [5] DEBUG GuideEnricher.tvdb.TvdbLibAccess - SD-TvDb: Search for Madam Secretary return 1 results
2015-03-09 06:45:17 [5] DEBUG GuideEnricher.tvdb.TvdbLibAccess - SD-TvDb: series: Madam Secretary id: 281623
2015-03-09 06:45:17 [5] DEBUG GuideEnricher.Enricher - Beginning enrichment of episodes for series Madam Secretary
2015-03-09 06:45:17 [5] DEBUG GuideEnricher.tvdb.TvdbLibAccess - Starting lookup for Madam Secretary - Tamerlane
2015-03-09 06:45:17 [5] DEBUG GuideEnricher.EpisodeMatchMethods.MatchMethodBase - [Episode Title] Correctly matched Madam Secretary - Tamerlane as S01E16
2015-03-09 06:45:17 [5] DEBUG GuideEnricher.tvdb.TvdbLibAccess - SD-TvDb: Search for Once Upon a Time (2011) return 1 results
2015-03-09 06:45:17 [5] DEBUG GuideEnricher.tvdb.TvdbLibAccess - SD-TvDb: series: Once Upon a Time (2011) id: 248835
2015-03-09 06:45:17 [5] DEBUG GuideEnricher.Enricher - Beginning enrichment of episodes for series Once Upon a Time
2015-03-09 06:45:17 [5] DEBUG GuideEnricher.tvdb.TvdbLibAccess - Starting lookup for Once Upon a Time - Enter the Dragon
2015-03-09 06:45:17 [5] DEBUG GuideEnricher.EpisodeMatchMethods.MatchMethodBase - [Episode Title] Could not match Once Upon a Time - Enter the Dragon
2015-03-09 06:45:17 [5] DEBUG GuideEnricher.EpisodeMatchMethods.MatchMethodBase - [Original Air Date] Could not match Once Upon a Time - Enter the Dragon
2015-03-09 06:45:17 [5] DEBUG GuideEnricher.EpisodeMatchMethods.MatchMethodBase - [Three or Four Digit Season Episode] Could not match Once Upon a Time - Enter the Dragon
2015-03-09 06:45:17 [5] DEBUG GuideEnricher.EpisodeMatchMethods.MatchMethodBase - [No Punctuation] Could not match Once Upon a Time - Enter the Dragon
2015-03-09 06:45:17 [5] DEBUG GuideEnricher.EpisodeMatchMethods.MatchMethodBase - [Remove common words] Could not match Once Upon a Time - Enter the Dragon
2015-03-09 06:45:17 [5] ERROR GuideEnricher.Service - Error enriching
System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Text.RegularExpressions.Regex.Match(String input)
   at GuideEnricher.EpisodeMatchMethods.FirstSentenceInDescriptionMatchMethod.Match(GuideEnricherProgram enrichedGuideProgram, List`1 episodes)
   at GuideEnricher.tvdb.TvdbLibAccess.EnrichProgram(GuideEnricherProgram existingProgram, TvdbSeries tvdbSeries)
   at GuideEnricher.Enricher.EnrichProgramsInSeries(GuideEnricherSeries series, TvdbSeries OnlineSeries)
   at GuideEnricher.Enricher.EnrichSeries(GuideEnricherSeries series)
   at GuideEnricher.Enricher.EnrichUpcomingPrograms()
   at GuideEnricher.Service.Enrich(Object state, ElapsedEventArgs eventArgs)

**Comment by Malyngo** [comment]
This bug (https://github.com/ChrisRichner/ARGUS-TV-GuideEnhancer/issues/8) should be fixed since version 2.3.1 
The "FirstSentenceInDescriptionMatchMethod" is using a Regex and wasn't checking if the value that should be checked is null, this causes the crash.

If you do not wish to upgrade right now, you can also disable the FirstSentenceInDescriptionMatchMethod and the InQuotesInDescriptionMatchMethod in the config. Those are the two match methods that are affected by this bug.

**Comment by aswede** [comment]
Excellent ... thanks!!
I'll upgrade when I get home this evening.

Anders

**Comment by ChrisRichner** [comment]
Hi Anders,

Any news about the issue you're faced?

**Comment by aswede** [comment]
Sorry for the delay in getting back to you ... like you suggested moving to
a more recent version of Guide Enhancer solved the problem. Thanks!

However, I have two other things to report.

I keep running in to the issue that when the same TV series program is
shown more then once the first time is enriched correctly, the second time
there is no enhancement. I am attaching a picture of what it looks like in
Argus - look at the show The Americans - the first time it looks OK, the
second time it is not enhanced.

Second issue is the Show "Black Sails" - it is usually not enhanced, and
when it is every episode is listed as S01E01. I am attaching a picture as
well.

I am also including the current log file from Guide Enhancer.

Anders

**Comment by ChrisRichner** [comment]
Hi aswede

Where did you include the mentioned screenshots?

Chris

**Comment by aswede** [comment]
Sorry for the delay in getting back to you. Screenshots included.

Anders
![black sails](https://cloud.githubusercontent.com/assets/10309505/6887636/3cf5633c-d62b-11e4-9a6d-55ed0089f0c7.jpg)
![the americans](https://cloud.githubusercontent.com/assets/10309505/6887638/3f78e5f2-d62b-11e4-9ce8-413548197247.jpg)

**Comment by ChrisRichner** [comment]
I see, are you able to share the xmltv file with me so that I can debug exactly your scenario?

**Comment by aswede** [comment]
Does this work? I could not find a way to attach a txt file.

Anders

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="seriesMapping" type="GuideEnricher.Config.SeriesNameMapsSection, GuideEnricherService" allowDefinition="Everywhere" allowExeDefinition="MachineToApplication" restartOnExternalChanges="true"/>
    <section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler, log4net"/>
    <section name="MatchMethodsSection" type="GuideEnricher.Config.MatchMethodsSection, GuideEnricherService"/>
  </configSections>
  
  <seriesMapping>
    <seriesMap schedulesDirectName="$..! Merlin" tvdbComName="id=83123" />
    <seriesMap schedulesDirectName="regex=The Bletchley Circle.*" tvdbComName="" ignore="true" />
    <seriesMap schedulesDirectName="regex=Reign.*" tvdbComName="Reign (2013)" />
    <seriesMap schedulesDirectName="regex=Kingdom.*" tvdbComName="Kingdom (2014)" />
    <seriesMap schedulesDirectName="regex=Scandal.*" tvdbComName="Scandal (2012)" />
    <seriesMap schedulesDirectName="regex=Hindsight.*" tvdbComName="Hindsight (2015)" />
    <seriesMap schedulesDirectName="regex=Hawaii Five-0.*" tvdbComName="id=164541" />
    <seriesMap schedulesDirectName="regex=The Layover With Anthony Bourdain.*" tvdbComName="id=252207" />
    <seriesMap schedulesDirectName="regex=Shameless.*" tvdbComName="id=161511" />
    <seriesMap schedulesDirectName="regex=Black Sails.*" tvdbComName="id=262407" />
    <seriesMap schedulesDirectName="regex=Secrets and Lies.*" tvdbComName="id=279214" />
    <seriesMap schedulesDirectName="regex=The Missing.*" tvdbComName="id=282401" />
    <seriesMap schedulesDirectName="regex=Dual Survival.*" tvdbComName="id=166991" />
    <seriesMap schedulesDirectName="regex=Nashville.*" tvdbComName="id=259055" />
    <seriesMap schedulesDirectName="regex=Marry Me.*" tvdbComName="id=281589" />
    <seriesMap schedulesDirectName="regex=Rookie Blue.*" tvdbComName="id=157631" />
    <seriesMap schedulesDirectName="regex=Mike Rowe's.*" tvdbComName="id=284791" />
    <seriesMap schedulesDirectName="regex=The Missing.*" tvdbComName="id=282401" />
    <seriesMap schedulesDirectName="regex=Parenthood.*" tvdbComName="id=94551" />
    <seriesMap schedulesDirectName="regex=Reckless.*" tvdbComName="id=269783" />
    <seriesMap schedulesDirectName="regex=The Flash.*" tvdbComName="id=279121" />
    <seriesMap schedulesDirectName="regex=Intruders.*" tvdbComName="id=277500" />
    <seriesMap schedulesDirectName="regex=Doctor Who.*" tvdbComName="id=78804" />
    <seriesMap schedulesDirectName="regex=The Bridge.*" tvdbComName="The Bridge (2013)" />
    <seriesMap schedulesDirectName="regex=Legends.*" tvdbComName="Legends (2014)" />
    <seriesMap schedulesDirectName="regex=Forever.*" tvdbComName="Forever (2014)" />
    <seriesMap schedulesDirectName="$..! Intelligence" tvdbComName="id=267260" />
    <seriesMap schedulesDirectName="regex=Through the Wormhole.*" tvdbComName="id=168571" />
    <seriesMap schedulesDirectName="regex=Outlander.*" tvdbComName="id=270408" />
    <seriesMap schedulesDirectName="regex=Welcome to Swe.*" tvdbComName="id=274123" />
    <seriesMap schedulesDirectName="regex=Bitten.*" tvdbComName="id=269550" />
    <seriesMap schedulesDirectName="regex=Intelligence.*" tvdbComName="Intelligence (2014)" />
    <seriesMap schedulesDirectName="$..! Reign" tvdbComName="id=269602" />
    <seriesMap schedulesDirectName="$..! The Eagle" tvdbComName="id=79579" />
    <seriesMap schedulesDirectName="$..! Bones" tvdbComName="id=75682" />
    <seriesMap schedulesDirectName="$..! Grimm" tvdbComName="id=248736" />
    <seriesMap schedulesDirectName="$..! Revenge" tvdbComName="id=248837" />
    <seriesMap schedulesDirectName="$..! The Big Bang Theory" tvdbComName="id=80379" />
    <seriesMap schedulesDirectName="$..! Revolution" tvdbComName="id=258823" />
    <seriesMap schedulesDirectName="$..! Rush" tvdbComName="id=280939" />
    <seriesMap schedulesDirectName="$..! Common Law" tvdbComName="id=253982" />
    <seriesMap schedulesDirectName="$..! Last Resort" tvdbComName="id=255413" />
    <seriesMap schedulesDirectName="$..! Breaking Bad" tvdbComName="id=81189" />
    <seriesMap schedulesDirectName="$..! It's Always Sunny in Philadelphia" tvdbComName="id=75805" />
    <seriesMap schedulesDirectName="$..! Modern Family" tvdbComName="id=95011" />
    <seriesMap schedulesDirectName="$..! SpongeBob SquarePants" tvdbComName="id=75886" />
    <seriesMap schedulesDirectName="$..! American Dad" tvdbComName="id=73141" />
    <seriesMap schedulesDirectName="$..! Body of Proof" tvdbComName="id=167591" />
    <seriesMap schedulesDirectName="$..! Hell On Wheels" tvdbComName="id=212961" />
    <seriesMap schedulesDirectName="$..! The Finder" tvdbComName="id=248651" />
    <seriesMap schedulesDirectName="$..! Being Human" tvdbComName="id=196921" />
    <seriesMap schedulesDirectName="$..! Once Upon a Time in Wonderland" tvdbComName="id=269654" />
    <seriesMap schedulesDirectName="$..! Adventure Time" tvdbComName="id=152831" />
    <seriesMap schedulesDirectName="$..! Leverage" tvdbComName="id=82339" />
    <seriesMap schedulesDirectName="$..! White Collar" tvdbComName="id=108611" />
    <seriesMap schedulesDirectName="$..! Alcatraz" tvdbComName="id=248646" />
    <seriesMap schedulesDirectName="$..! Dirty Jobs" tvdbComName="id=78904" />
    <seriesMap schedulesDirectName="$..! The River" tvdbComName="id=248836" />
    <seriesMap schedulesDirectName="$..! Suits" tvdbComName="id=247808" />
    <seriesMap schedulesDirectName="$..! Harry's Law" tvdbComName="id=163581" />
    <seriesMap schedulesDirectName="$..! House" tvdbComName="id=73255" />
    <seriesMap schedulesDirectName="$..! How I  Met Your Mother" tvdbComName="id=75760" />
    <seriesMap schedulesDirectName="$..! Hot in Cleveland" tvdbComName="id=162071" />
    <seriesMap schedulesDirectName="$..! Deadliest Catch" tvdbComName="id=78957" />
    <seriesMap schedulesDirectName="$..! Up All Night" tvdbComName="id=248943" />
    <seriesMap schedulesDirectName="$..! The Mentalist" tvdbComName="id=82459" />
    <seriesMap schedulesDirectName="$..! MythBusters" tvdbComName="id=73388" />
    <seriesMap schedulesDirectName="$..! Lost Girl" tvdbComName="id=182061" />
    <seriesMap schedulesDirectName="$..! The Walking Dead" tvdbComName="id=153021" />
    <seriesMap schedulesDirectName="$..! Touch" tvdbComName="id=248935" />
    <seriesMap schedulesDirectName="$..! South Park" tvdbComName="id=75897" />
    <seriesMap schedulesDirectName="$..! Rizzoli &amp; Isles" tvdbComName="id=161461" />
    <seriesMap schedulesDirectName="regex=NCIS Los.*" tvdbComName="id=95441" />
    <seriesMap schedulesDirectName="regex=The Americans.*" tvdbComName="The Americans (2013)" />
    <seriesMap schedulesDirectName="regex=Up All Nig.*" tvdbComName="id=248943" />
    <seriesMap schedulesDirectName="regex=Being Huma.*" tvdbComName="id=196921" />
    <seriesMap schedulesDirectName="regex=Betrayal.*" tvdbComName="id=269647" />
    <seriesMap schedulesDirectName="regex=Spartacus.*" tvdbComName="id=129261" />
    <seriesMap schedulesDirectName="regex=The Tomorro.*" tvdbComName="id=268591" />
    <seriesMap schedulesDirectName="regex=Body of Proo.*" tvdbComName="Body of Proof" />
    <seriesMap schedulesDirectName="regex=Hell on Whee.*" tvdbComName="Hell on Wheels" />
    <seriesMap schedulesDirectName="regex=Prime Sus.*" tvdbComName="Prime Suspect (US)" />
    <seriesMap schedulesDirectName="regex=Wilfred" tvdbComName="Wilfred (US)" />
    <seriesMap schedulesDirectName="regex=American Horror Story.*" tvdbComName="American Horror Story" />
    <seriesMap schedulesDirectName="Castle" tvdbComName="Castle (2009)" />
    <seriesMap schedulesDirectName="Boss" tvdbComName="Boss (2011)" />
    <seriesMap schedulesDirectName="Once Upon a Time" tvdbComName="Once Upon a Time (2011)" />
    <seriesMap schedulesDirectName="Zero Hour" tvdbComName="Zero Hour (2013)" />
    <seriesMap schedulesDirectName="The Killing" tvdbComName="The Killing (2011)" />
    <seriesMap schedulesDirectName="Touch" tvdbComName="Touch (2012)" />
    <seriesMap schedulesDirectName="Golden Boy" tvdbComName="Golden Boy (2013)" />
    <seriesMap schedulesDirectName="Atlantis" tvdbComName="Atlantis (2013)" />
    <seriesMap schedulesDirectName="Battlestar Galactica" tvdbComName="Battlestar Galactica (2003)" />
    <seriesMap schedulesDirectName="The Honorable Woman" tvdbComName="The Honourable Woman" />
    <seriesMap schedulesDirectName="Last Man Standing" tvdbComName="Last Man Standing (2011)" />
    <seriesMap schedulesDirectName="Beauty and the Beast" tvdbComName="Beauty and the Beast (2012)" />
    <seriesMap schedulesDirectName="The Office" tvdbComName="The Office (US)" />
    <seriesMap schedulesDirectName="Archer" tvdbComName="Archer (2009)" />
    <seriesMap schedulesDirectName="River Monsters: Unhooked" tvdbComName="River Monsters" />
    <seriesMap schedulesDirectName="Louie" tvdbComName="Louie (2010)" />
    <seriesMap schedulesDirectName="Ironside" tvdbComName="Ironside (2013)" />
  </seriesMapping>
  
  <MatchMethodsSection>
    <MatchMethods>
      <add name="GuideEnricher.EpisodeMatchMethods.RemoveCommonWordsMatchMethod"/>
      <add name="GuideEnricher.EpisodeMatchMethods.EpisodeTitleMatchMethod"/>
      <add name="GuideEnricher.EpisodeMatchMethods.SeasonAndEpisodeInDescriptionMatchMethod"/>
      <add name="GuideEnricher.EpisodeMatchMethods.FirstSentenceInDescriptionMatchMethod"/>
      <add name="GuideEnricher.EpisodeMatchMethods.AirDateMatchMethod"/>
      <add name="GuideEnricher.EpisodeMatchMethods.AbsoluteEpisodeNumberMatchMethod" />
      <add name="GuideEnricher.EpisodeMatchMethods.NumericSeasonEpisodeMatchMethod"/>
      <add name="GuideEnricher.EpisodeMatchMethods.NoPunctuationMatchMethod"/>
      <add name="GuideEnricher.EpisodeMatchMethods.SeasonAndEpisodeInDescriptionMatchMethod"/>
      <add name="GuideEnricher.EpisodeMatchMethods.InQuotesInDescriptionMatchMethod"/>
    </MatchMethods>
  </MatchMethodsSection>
  <log4net>
    <appender name="RollingLogFileAppender" type="log4net.Appender.RollingFileAppender">
      <file value="guideenricher.log"/>
      <appendToFile value="true"/>
      <maxSizeRollBackups value="10"/>
      <maximumFileSize value="5MB"/>
      <rollingStyle value="Size"/>
      <staticLogFileName value="true"/>
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%date{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger - %message%newline"/>
      </layout>
    </appender>
    <appender name="Console" type="log4net.Appender.ConsoleAppender">
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%message%newline"/>
      </layout>
    </appender>
    <root>
      <level value="DEBUG"/>
      <appender-ref ref="RollingLogFileAppender"/>
      <appender-ref ref="Console"/>
    </root>
    
  </log4net>
  <appSettings>
    
    <add key="TvDbLibCache" value="c:\\tvdblibcache\\"/>
    
    <add key="TvDbLanguage" value="en"/>
    
    <add key="sleepTimeInHours" value="12"/>

    
    <add key="maxShowNumberPerUpdate" value="20"/>

    
    <add key="ftrUrlHost" value="localhost"/>
    <add key="ftrUrlPort" value="49943"/>
    
    <add key="ftrUserName" value=""/>
    <add key="ftrUrlPassword" value=""/>
    
    <add key="dumpepisodes" value="false"/>
    
    <add key="updateAll" value="false"/>
    
    <add key="episodeInDescription" value="false"/>
    
    <add key="updateSubtitles" value="false"/>
  </appSettings>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5"/>
  </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-2.6.8.0" newVersion="2.6.8.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Threading.Tasks" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-2.6.8.0" newVersion="2.6.8.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>

**Comment by aswede** [comment]
Perhaps I misunderstood what you asked for .. I am using SchedulesDirect to receive the EPG in XML format. I used the Getdata command but the xml file is too big to copy paste here. Can I send you / upload an attachement somehow?

**Comment by Christoph21x** [comment]
Hi Anders!
I followed this issue and your problems and I've got some questions - could you please check them and reply to all/each of them?

I start with the screenshot that you uploaded:
1. What I see, is that the same episode of "The Americans" first was recognized, the second broadcast not. You also mentioned "Sleepy Hollow" - but that's not shown on the screenshot
--> My question: is it always a repetition of an episode that is not recognized or was this just an incidence?
2. Can you describe the Argus schedule for these series?
2.1 Is it "record only once"?
2.2 Does it have other conditions (other than default) set?
3. You say you get EPG through SchedulesDirect.
3.1 Do you get both, XMLTV import AND EPG? Or only EPG?
3.2 If both, what is your Argus setting (Scheduler->Settings)? XMLTV overwrites EPG or vice-versa?

From my perception, from what you describe, this could also be a SYSTEM issue (combination of systems) than a pure EG one...

Greetz - Chris

**Comment by aswede** [comment]
Can I email you the file? 

Anders
