### ISSUE TITLE
Implement case INsensitive search (in at least: mapping)

### ISSUE THREAD

**Issue by Christoph21x** [ChrisRichner/ARGUS-TV-GuideEnhancer#19]
Dear All, dear Chris

I encountered a season, that couldn't be dispatched, although mapped by id.
I found out, that the search (at least for mappings; probably for all searches?), must be case sensitive. I changed the mapping entry - and it worked.
As TV guide providers might be a bit sloppy, implementing a case-insensitive search may ameliorate the hit rate.
In my earlier programming days, I had developed a "normalization algorithms" for such searches, treating any kind of potential misspellings, umlauts, etc. Could be in a second step also an idea.

I'll upload the changed mapping entry to the repository for the time being.

Greetz - Chris

**Comment by ChrisRichner** [comment]
Fixed in vNext, thanks for bringing this up!
