### ISSUE TITLE
Severe: no enrichment with 2.3.3. release anymore

### ISSUE THREAD

**Issue by Christoph21x** [ChrisRichner/ARGUS-TV-GuideEnhancer#20]
With the update to the new version not any enrichment takes place on my system!

I see for any series (even those that are not programmed) the following (same) pattern:
2015-04-17 10:16:06 [175] DEBUG GuideEnricher.tvdb.TvdbLibAccess - Starting lookup for Grimm - 
2015-04-17 10:16:06 [175] DEBUG GuideEnricher.EpisodeMatchMethods.MatchMethodBase - [Episode Title] Grimm - 04/28 10:10 PM does not have a "SubTitle"
2015-04-17 10:16:06 [175] DEBUG GuideEnricher.EpisodeMatchMethods.AbsoluteEpisodeNumberMatchMethod - Cannot use match method [Absolute Episode Number] Grimm does not have an episode number
2015-04-17 10:16:06 [175] DEBUG GuideEnricher.EpisodeMatchMethods.MatchMethodBase - [Remove common words] Grimm - 04/28 10:10 PM does not have a "SubTitle"
2015-04-17 10:16:06 [175] DEBUG GuideEnricher.EpisodeMatchMethods.MatchMethodBase - [Three or Four Digit Season Episode] Could not match Grimm - 
2015-04-17 10:16:06 [175] DEBUG GuideEnricher.EpisodeMatchMethods.MatchMethodBase - [No Punctuation] Grimm - 04/28 10:10 PM does not have a "SubTitle"
2015-04-17 10:16:06 [175] DEBUG GuideEnricher.EpisodeMatchMethods.MatchMethodBase - [Season and Episode in Description] Could not match Grimm - 
2015-04-17 10:16:06 [175] DEBUG GuideEnricher.Enricher - The first run for the series Grimm had unmatched episodes.  Checking for online updates.

You can freely exchange the series names...

Greetz - Chris

PS: if others face this, too, we IMMEDIATELY need to inform in the forum thread and supply the former version - and for us development supporter the latest "patch" with case INsensitive search.

**Comment by ChrisRichner** [comment]
Hi Chris

Thanks for warning us about this behaviour. Is the Subtitle really missing in your program guide? The quickly made tests I've made so far didn't show any unexpected results.

**Comment by Christoph21x** [comment]
Hi Chris
Nothing has changed except the installation of the release.
Episode titles are present as before, GE is connectd to Argus, just no enrichment (also stated in the Argus Log). What could I do to investigate?
Greetz - Chris

**Comment by ChrisRichner** [comment]
Please do a clean install to make sure the problems didn't come from a invalid upgrade.

**Comment by Christoph21x** [comment]
Hey Chris
OK - uninstalled Guide Enricher properly and found FOUR installations in the meantime of GE - one even forced me (even though the service was long since quitted) to reboot the system:
![zwischenablage01](https://cloud.githubusercontent.com/assets/1575363/7220300/6b8317ce-e6c2-11e4-944f-cdb23e8800ca.jpg)

Installed the Release - now we wait for tomorrow.

1. Noone dropped a message "me too" or complained in the Argus' forums
2. My system was abviously messed up with GE installs
3. If it works by tomorrow, I'll drop a message and close this issue.

Greetz - Chris

**Comment by ChrisRichner** [comment]
Fair enough, cross fingers 😊👍 

-----Original Message-----

**Comment by Christoph21x** [comment]
Hi to All

Unfortunately - no success. GE shows in version 2.3.3 with clean install exactly the same behaviour: no enrichment (which is correctly stated in Argus' log files, too).

After manually exchanging the following files, it worked correctly as before:
- Tvdblib.lib (as per 02.03.2015)
- Tvdblib.dll (as per 02.03.2015)
- GuideEnricherService.exe (as per 29.03.2015; case INsensitive test version)
- GuideEnricherService.pdb (as per 29.03.2015; case INsensitive test version)

Greetz - Chris

**Comment by ChrisRichner** [comment]
I've flagged the release as a non production release. I hope to find some spare time in the days to come to analyse the issues. On my test system the develop branch ( which should be the same code as in the release) works fine..

**Comment by Christoph21x** [comment]
Ok, some update:
1. I made an uninstall again, found some uninstall issues - a separate issue - I will open it (minor priority) after this.
2. I made a manual wipe (due to uninstall  issue necessary)
3. I made a clean install after reboot - same result.
4. I compared the installations 
   4.1 (some resultless steps in betwenn & roll-backs)
   4.2 and finally ONLY exchanged GuideEnricherService.exe with the older version - it worked.

Suggestion: send me (just) your exe coming out of the build of the final development branch - I'll test it. If positive, we have a difference between the development branch and the release. Even though "it shouldn't be" (I think the topmost of all SW errors come out of this category).

Deal?

Chris

**Comment by ChrisRichner** [comment]
Deal 😊 

-----Original Message-----

**Comment by Christoph21x** [comment]
Ok, here are the results of the Bern Jury :)
You sent me the two exe files of _develop and _master branch.
Plan was, 1st to install the _develop version, if successful, 2nd to try the _master version.

Unfortunately already the _development's exe failed and showed the same behaviour as initially described: no enrichtment.

I think, we now need a kind of debug version, which focuses on the analysis of the xmtlv reading. Why it can't detect any of the information: subtitle and season/episode number in xmltv - this is how it looks like to me.
These reflect the first three search priorities (episode name, relative numbering, absolute numbering) on my system.

Greetz - Chris

**Comment by ChrisRichner** [comment]
Jury of Bern <g>

Looks like the branching and merging is not the problem, neither the msi setup building process. 

On my test system everything works like a charm using the following setup
- W++ to grab the xmltv
- ARGUS-TV 2.3.0 RTM
- Latest 2.3.3 GE setup ( as found here on github )

any body else facing this issue as Chris does?

**Comment by Christoph21x** [comment]
Exactly same setting here - but it's not enriching.

**Comment by Christoph21x** [comment]
Problem solved with the newest commit of Chris - tested & approved.
Chris found the issue - will be corrected with the next commit.
