### ISSUE TITLE
Capaciry limit of seriesMap?

### ISSUE THREAD

**Issue by Christoph21x** [ChrisRichner/ARGUS-TV-GuideEnhancer#23]
Hi All

I think, I reached the capacity limit of seriesMap entries.
Since I added the most recent 2 mappings, GE didn't start anymore.
If I start it manually, I get the message:
"Services ¦ Error 14001 [...] Side-by-Side configuration is invalid" - see attachment:
![zwischenablage01](https://cloud.githubusercontent.com/assets/1575363/9094042/ff7ab62a-3baf-11e5-858a-13360b0c0045.jpg)

The Windows Protocol / Application shows: 
![zwischenablage02](https://cloud.githubusercontent.com/assets/1575363/9094136/771d5b42-3bb0-11e5-87f9-2f1bc07f750f.jpg)
But the text is not correct.. If I remove one or two entries - no matter which - it is startable again

GReetz - Chris

PS: ask me - I can send you the "non-working config"

**Comment by ChrisRichner** [comment]
I've checked the config file you've sent. Turns out there was a missing " char making the XML file invalid. The log message in the screenshot Shows that is an error at line 70.
